#pragma once
enum COLLISION_TYPE
{
	COLLISION_TYPE_GROUND,
	COLLISION_TYPE_ENEMY,
	COLLISION_TYPE_GATE,
	COLLISION_TYPE_STAIR,
	COLLISION_TYPE_STATIC_OBJECT,
	COLLISION_END_STAIR,
	COLLISION_ITEM,
	COLLISION_TYPE_PLAYER,
	COLLISION_TYPE_MORNING_STAR,

	/* số lượng collisionType luôn nằm cuối */
	COLLISION_TYPE_COUNT
};